AllCops:
  DisplayCopNames: true

Style/FileName:
  Exclude:
    - lib/rubocop-gemfile.rb

Style/Documentation:
  Exclude:
    - 'lib/rubocop/cop/gemfile/concerns/**/*.rb'
    # rubocop default setting
    - 'spec/**/*'
    - 'test/**/*'
