sudo: false
language: ruby
rvm:
- 2.2
- 2.3.1
- ruby-head
before_install: gem install bundler -v 1.12.5

bundler_args: "--jobs=2"
cache: bundler
before_script:
- export CODECLIMATE_REPO_TOKEN=
- export CI=true
script:
- bundle exec rspec
- bundle exec rubocop
branches:
  only:
  - master
notifications:
  email: false
matrix:
  allow_failures:
  - rvm: ruby-head
