AllCops:
  Gemfile:
    Patterns:
    - "Gemfile"

Gemfile/SingleGroup:
  Description: "Check that `group` method has single group name"
  Enabled: true

Gemfile/GroupType:
  Description: "Use enforced type group"
  EnforcedStyle: symbol
  SupportedStyles:
    - symbol
    - double_quotes
    - single_quotes
  Enabled: true

Gemfile/SortGemAscending:
  Description: "Sort the gem in alphabetical order"
  Enabled: true
